### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by woopstar** [Bouni/esphome-bwt-sensor#3]
How has this been working for you, so far?

Can you add a picture of how you mounted it?

**Comment by Bouni** [comment]
It worked really well for me so far!

I've just mounted it using tape, no good solution but does the job.

![IMG_20220118_202452.jpg](https://user-images.githubusercontent.com/948965/232071894-9ec9dda8-a827-49f2-ad8d-f4c9b105f6a2.jpg)

**Comment by woopstar** [comment]
Great. Thanks for the update. I'll try to compose one myself.

For anyone else who might stumble upon this repo, this is what I have ordered:

https://www.aliexpress.com/item/1005005296493767.html?spm=a2g0o.order_list.order_list_main.11.19cc1802X6rQEv
and
https://www.aliexpress.com/item/1005004605382610.html?spm=a2g0o.order_list.order_list_main.5.19cc1802X6rQEv

Wiring can be found here:

http://www.esp32learning.com/code/esp32-and-tcs34725-color-sensor.php

And esphome config for the ESP8266:
https://pastebin.com/ma9uyMML


I will give an update when I have received the parts and if everything works as expected.

**Comment by woopstar** [comment]
Can confirm it works with D1 . Have not yet tried running out of salt.

Working ESPHome code for D1 with the color sensor:

```yaml
esphome:
  name: bwt
  friendly_name: bwt

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "bwt Fallback Hotspot"
    password: "12345678"

captive_portal:

i2c:
 # sda: D2
 # scl: D1
  scan: true
  #id: i2cbus

sensor:
  - platform: tcs34725
    red_channel:
      id: bwt_red
      name: "BWT Red"
    green_channel:
      id: bwt_green
      name: "BWT Green"
    blue_channel:
      id: bwt_blue
      name: "BWT Blue"
    clear_channel:
      id: bwt_clear
      name: "BWT Clear"
    illuminance:
      id: bwt_illuminance
      name: "BWT Illuminance"
    color_temperature:
      id: bwt_color_temperature
      name: "BWT Color Temperature"
    gain: 60x
    glass_attenuation_factor: 5.0
    integration_time: 614ms
    update_interval: 10s

  - platform: uptime
    name: "bwt Uptime"

  - platform: wifi_signal
    name: "bwt Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "bwt IP Address"
    ssid:
      name: "bwt Wi-Fi SSID"
    bssid:
      name: "bwt Wi-Fi BSSID"

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  - platform: template
    name: "BWT State"
    lambda: |-
      if (id(bwt_blue).state > id(bwt_green).state  && id(bwt_blue).state > id(bwt_red).state) {
        return {"Normal"};
      } else if (id(bwt_green).state > id(bwt_red).state  && id(bwt_green).state > id(bwt_blue).state) {
        return {"Regeneration"};
      } else if (id(bwt_red).state > id(bwt_blue).state && id(bwt_red).state > id(bwt_green).state) {
        return {"Error"};
      } else {
        return {"Unknown"};
      }
    update_interval: 5s

switch:
  - platform: restart
    name: "Restart"
    id: switch_restart
```
